### ISSUE TITLE
Feature request: Integrate with `company-mode`

### ISSUE THREAD

**Issue by Yevgnen** [casouri/eldoc-box#10]
Hi, thanks for the great package. It will be awesome if it is possible to integrate `eldoc-box` with `company-mode`, just like `company-quickhelp-mode` which uses `pos-tip` instead of childframe.

<img width="687" alt="screen shot 2019-01-10 at 13 04 11" src="https://user-images.githubusercontent.com/16749790/50947238-3d924b80-14d8-11e9-8c27-7ec222f5a5f9.png">

**Comment by casouri** [comment]
Thanks. If you mean adding childframe display for company, there are [company-box](https://github.com/sebastiencs/company-box) and [company-posframe](https://github.com/tumashu/company-posframe).

**Comment by Yevgnen** [comment]
I mean childframe display for documentation for `company` just like `company-quickhelp`. `company-box` is buggy and lack of maintenance while `company-posframe` works for `company` candidates but not for documentations.

**Comment by casouri** [comment]
In that case, I might have to disappoint you again 😢 

eldoc-box, as the name suggests, is only for eldoc. The majority of the code deals with eldoc and smoothes its rough edges (when using childframe instead of minibuffer).

IMO the right approach would be to upgrade company-quickhelp to display doc in a childframe. It should be easy with posframe, or a custom function like `eldoc-box--display`. Another way is to upgrade company-posframe, of course.

**Comment by Yevgnen** [comment]
Thanks!
